# Generated by Django 2.1b1 on 2018-07-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0002_auto_20180504_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_line', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=3)),
                ('line_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.AddField(
            model_name='contentline',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soup.Content'),
        ),
    ]
