# Generated by Django 2.1b1 on 2018-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0003_auto_20180712_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(max_length=256),
        ),
    ]
