# Generated by Django 2.1b1 on 2018-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0004_auto_20180712_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contentline',
            name='content_line',
            field=models.CharField(max_length=256),
        ),
    ]
