# Generated by Django 2.1b1 on 2018-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0005_auto_20180712_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentline',
            name='content_line',
            field=models.TextField(),
        ),
    ]
