# Generated by Django 2.1b1 on 2018-07-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0006_auto_20180712_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentline',
            old_name='content_id',
            new_name='content',
        ),
    ]
